name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and run tests
    # runs-on: ubuntu-latest
    runs-on: macos-latest # Switched to macOS
    steps:
      - name: Checkout current repository in ubuntu's file system 
        uses: actions/checkout@v1
      
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Print contents in current directory
        run: ls -la
        
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          avd-name: test
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck
          
      - name: Upload Reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: currency-formatter/build/reports
            
      - name: jacoco-badge-generator
        uses: cicirello/jacoco-badge-generator@v1.0.0

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        
      - name: Create pull request
        if: ${{ github.event_name == 'push' }}
        uses: peter-evans/create-pull-request@v3.4.1
        with:
          title: "Autogenerated Jacoco Coverage Badge"
          body: > 
            Autogenerated Jacoco coverage badge, generated by 
            the [jacoco-badge-generator](https://github.com/cicirello/jacoco-badge-generator) 
            GitHub action.
          commit-message: "Autogenerated Jacoco Coverage Badge"
          branch: create-pull-request/badge
          delete-branch: true


